[env:m5stack-coreink]
platform = espressif32
board = m5stack-coreink
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

lib_deps =
    m5stack/M5Unified@^0.2.2
    m5stack/M5GFX@^0.2.3
    bblanchon/ArduinoJson@^7.3.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM=0
    -DBOARD_COREINK

[env:m5stick-cplus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000

lib_deps =
    m5stack/M5Unified@^0.2.2
    m5stack/M5GFX@^0.2.3
    bblanchon/ArduinoJson@^7.3.0

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_M5STICK_CPLUS2
